FROM debian:trixie@sha256:913f6706df59a68922d1dd08f78c2476560a8d367897200a6005b00e5f67c2d5
RUN apt-get update -qq && apt-get install -qq -y --no-install-recommends nftables && rm -rf /var/lib/apt/lists/*
