#!/bin/bash
if [[ -e /var/lib/doitpi/firstboot.done ]]; then
    echo "DoItPi: Erster Start abgeschlossen."
else
    echo "DoItPi: Erster Start läuft noch oder ist fehlgeschlagen."
    echo "        Details: journalctl -u doitpi_firstboot.service"
fi